In [1]:
import  numpy as  np
a = np.array([10,20,30])
b = np.array([50,40,70])
c = np.array(4)
print(a)
print(b)
print(a+b)
print(a*c)
print(a-b)

[10 20 30]
[50 40 70]
[ 60  60 100]
[ 40  80 120]
[-40 -20 -40]


In [2]:
%timeit result = [j**4 for j in range(1,9)]

670 ns ± 46.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
import numpy as np
%timeit np.arange(1,9)**4

4.13 μs ± 928 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#**Creating Numpy Arrays**

In [5]:
# list

l1 = [10,20,30]
l2 = [40,50,60]
print(l1+l2)

[10, 20, 30, 40, 50, 60]


In [7]:
# list

l1 = [10,20,30]
l2 = 4
print(l1*l2)

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]


In [25]:
ar = np.array([20,45,'60'])
ar1 = np.array([20,45,60.0])
print(ar)
print(ar1)

['20' '45' '60']
[20. 45. 60.]


In [29]:
l1 = [[10,20,30],[40,50]]
print(l1)

[[10, 20, 30], [40, 50]]


In [7]:
l1 = np.array([[10, 20, 30], [40, 50]], dtype=object)


In [33]:
l1 = np.array([[10,20],[40,50]])
print(l1)

[[10 20]
 [40 50]]


### slicing

In [47]:
import  numpy as  np
a = np.array([10,20,30])
print(a[1:3])
print(a[:2])
print(a[3:])
print(a[1:3:2])
print(type(a))

[20 30]
[10 20]
[]
[20]
<class 'numpy.ndarray'>


In [54]:
a = np.array([[10,20,30],[60,70,80]])
print(a[:2])
print(a[0])
print(a[-1])


[[10 20 30]
 [60 70 80]]
[10 20 30]
[60 70 80]


In [88]:
a = np.array([[10,20,30],[60,70,80]])
print(a[0:3,0:1])
print(a[0:2,0:2])
print(a[0,0])
print(a[:1-1,-3:1])
print(a[0,1:3])
print(a[0,2:3])

[[10]
 [60]]
[[10 20]
 [60 70]]
10
[]
[20 30]
[30]


In [106]:
a = np.array([[10,20,30],[60,70,80],[40,50,90]])
print(a[2,2])
print(a[0,0])
print(np.shape(a))
print(np.shape(a))
print(np.ndim(a))
print(a.dtype)

90
10
(3, 3)
(3, 3)
2
int32


## Inspecing  Array

In [134]:
import numpy as np

a = [20,40,60],[40,50,55]
arr = np.array(a)
print(arr)
print(arr.shape)                  #rows,columns
print(len(arr))      # num of nested values and total num of elements
print(np.size(arr))           # num of elements
print(type(arr))    # datatype of variable
print(arr.dtype)   # datatype of array
print(arr.astype(float))  # converion of datatype(change)
print(arr.astype(float))
print(arr.astype(str))

[[20 40 60]
 [40 50 55]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int32
[[20. 40. 60.]
 [40. 50. 55.]]
[[20. 40. 60.]
 [40. 50. 55.]]
[['20' '40' '60']
 ['40' '50' '55']]


## methematical operation and fumtions on Array

In [172]:
import numpy as np
a1 = np.array([3,5,7,4,3])
a2 = np.array([6,8,9,7,6,])
print(a1+a2)
print(np.add(a1,a2))

[ 9 13 16 11  9]
[ 9 13 16 11  9]


In [164]:
print(np.subtract(a1,a2))
print(a1-a2)

[-3 -3 -2 -3 -3]
[-3 -3 -2 -3 -3]


In [166]:
print(a1*a2)
print(np.multiply(a1,a2))

[18 40 63 28 18]
[18 40 63 28 18]


In [168]:
print(a1/a2)
print(np.divide(a1,a2))

[0.5        0.625      0.77777778 0.57142857 0.5       ]
[0.5        0.625      0.77777778 0.57142857 0.5       ]


In [176]:
import numpy as np
a1 = np.array([3,5,7,4,3])
a2 = np.array([2])
print(np.power(a1,a2))

[ 9 25 49 16  9]


In [182]:
ar = np.array([9, 25, 49, 16, 9])
print(np.sqrt(ar))
print(ar.astype(int))

[3. 5. 7. 4. 3.]
[ 9 25 49 16  9]


## Combining and splitting Array

In [191]:
a = [10,30,40]
b = [3,8,4]
print(a+b)

[10, 30, 40, 3, 8, 4]


In [ ]:
# concatenate / join

In [203]:
import numpy as np
a1 = np.array([10,30,40])
a2 = np.array([3,8,4])
print(np.concatenate([a1,a2]))

[10 30 40  3  8  4]


In [207]:
print(np.concatenate([a1,a2],axis = 0))
print(np.concatenate([a1,a2],axis = 1))

[10 30 40  3  8  4]


AxisError: axis 1 is out of bounds for array of dimension 1

In [217]:
import numpy as np

a1 = np.array([[10, 30], [20, 40]])
a2 = np.array([[3, 8], [7, 4]])   # extra brackets to make it 2D

print(np.concatenate([a1, a2], axis=1))
print(np.concatenate([a1, a2], axis=0))


[[10 30  3  8]
 [20 40  7  4]]
[[10 30]
 [20 40]
 [ 3  8]
 [ 7  4]]


In [11]:
import numpy as np

a1 = np.array([[10, 30], [20, 40]])
a2 = np.array([[3, 8], [7, 4]])             # horizontal concateate
print(np.hstack([a1,a2]))

[[10 30  3  8]
 [20 40  7  4]]


In [13]:
import numpy as np

a1 = np.array([[10, 30], [20, 40]])
a2 = np.array([[3, 8], [7, 4]])             # vertical concateate
print(np.vstack([a1,a2]))

[[10 30]
 [20 40]
 [ 3  8]
 [ 7  4]]


In [29]:
import numpy as np
#a = np.array([3,4,6,6,8,7])
#print(np.array_split(a,3))
a = np.array([[10,20,30],[40,50,30]])
b = np.array_split(a,4)
print(b[2])
print(b)

[]
[array([[10, 20, 30]]), array([[40, 50, 30]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]


## adding to removing elements in the array

In [41]:
import numpy as np
#a = np.array([20,30,40])
a = np.array([[20,30],[10,40]])
print(np.append(a,[60,80]))

[20 30 10 40 60 80]


In [47]:
print(np.insert(a,1,[50,60], axis = 1))      
print(np.insert(a,1,[50,60], axis = 1))      # array,index,value
print(np.insert(a,[1,2],[50], axis = 0))      

[[20 50 30]
 [10 60 40]]
[[20 50 30]
 [10 60 40]]
[[20 30]
 [50 50]
 [10 40]
 [50 50]]


In [53]:
print(np.delete(a,1))
print(np.delete(a,2))

[20 10 40]
[20 30 40]


In [67]:
print(a)
print(np.delete(a,1, axis = 1))


[[20 30]
 [10 40]]
[[20]
 [10]]


## search short and filter in array

In [82]:
import numpy as np

a = np.array([[5,3,4,2,3,1],[6,7,4,7,9,8]])
print(np.sort(a))

[[1 2 3 3 4 5]
 [4 6 7 7 8 9]]


In [92]:
import numpy as np
a = np.array([2,3,4,5,6])
s = np.where(a == 4) 
s = np.where(a % 2 == 0) 
print(s)

(array([0, 2, 4], dtype=int64),)


In [98]:
import numpy as np
a = np.array([2,3,4,5,6])
ss = np.searchsorted(a,4)
print(ss)

2


In [104]:
import numpy as np
a = np.array([20,30,40,50])
fa = [True,False,True,False]
fa = [True,False,True,False]
fa = [True,False,False,False]
new = a[fa]
print(new)

[20]


In [108]:
import numpy as np
a = np.array([20,30,40,50])
fa = a>35
new = a[fa]
print(new)

[40 50]


## aggregating functions in numpy

In [126]:
import numpy as np
a = np.array([20,30,70,49])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.size(a))
print(np.cumsum(a))

169
70
20
4
4
[ 20  50 120 169]


In [25]:
import numpy as np

a = [100, 130, 200, 150, 200]
b = [20, 12, 50, 20, 60]

price = np.array(a)
quantity = np.array(b)

print("Price array:", price)
print("Quantity array:", quantity)
print("Sum of prices:", np.sum(price))
print()
print(np.cumsum([price,quantity]))
print()
c = np.cumprod([price,quantity], axis = 0)
print(c[1].sum())

Price array: [100 130 200 150 200]
Quantity array: [20 12 50 20 60]
Sum of prices: 780

[100 230 430 580 780 800 812 862 882 942]

28560


In [13]:
import numpy as np

a = [100, 130, 200, 150, 200]
b = [20, 12, 50, 20, 60]

price = np.array(a)
quantity = np.array(b)

print("Price array:", price)
print("Quantity array:", quantity)

# Sum of prices
print("Sum of prices:", np.sum(price))

# Cumulative sum of each array separately
print("Cumulative sum of prices:", np.cumsum(price))
print("Cumulative sum of quantities:", np.cumsum(quantity))

# Element-wise product of price and quantity
print("Element-wise product:", price * quantity)

# Cumulative product of each array separately
print("Cumulative product of prices:", np.cumprod(price))
print("Cumulative product of quantities:", np.cumprod(quantity))


Price array: [100 130 200 150 200]
Quantity array: [20 12 50 20 60]
Sum of prices: 780
Cumulative sum of prices: [100 230 430 580 780]
Cumulative sum of quantities: [ 20  32  82 102 162]
Element-wise product: [ 2000  1560 10000  3000 12000]
Cumulative product of prices: [      100     13000   2600000 390000000 690588672]
Cumulative product of quantities: [      20      240    12000   240000 14400000]


## Statistical Functions

In [52]:
import numpy as np
import statistics as stats
baked_food = [100,150,300,200,240]
a = np.array(baked_food)
print(np.mean(baked_food))    # sum of all the value /number of values
print(np.median(baked_food))
print(stats.mode(baked_food))

198.0
200.0
100


In [14]:
# 1 represent inversaly proportnal relationship
# 1 represent  proportnal relationship
# 0 mean no relationship
import numpy as np
tobacco_consumption = [20,30,40,50,60]
deaths = [120,100,220,300,400]
print(np.corrcoef([tobacco_consumption,deaths]))


[[1.         0.95842322]
 [0.95842322 1.        ]]


In [16]:
price = [130,140, 150, 160,170]
sales = [5,3,6,8,7]
print(np.corrcoef([price,sales]))

[[1.         0.73979544]
 [0.73979544 1.        ]]


In [1]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))


[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [26]:
import numpy as np
x = [1,2,3,4]
y= np.array(x)
print(x)
print(y)
print(type(y))
print(y.ndim)

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>
1


In [23]:
l = []

for i in range(1,5):
    int_l = int(input('enter:'))
    l.append(int_l)
print(np.array(l))



enter: 12
enter: 13
enter: 14
enter: 15


[12 13 14 15]


# types of array

In [30]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [32]:
import numpy as np

x = np.array([[1,2,3,4]])
print(x)
print(type(x))
print(x.ndim)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2


In [34]:
import numpy as np

x = np.array([[[1,2,3,4]]])
print(x)
print(type(x))
print(x.ndim)

[[[1 2 3 4]]]
<class 'numpy.ndarray'>
3


In [42]:
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar)
print(type(ar.ndim))
print(ar.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'int'>
2


In [44]:
ar = np.array([[[1,2,3,4],[5,6,7,8],[9,2,5,7]]])
print(ar)
print(type(ar.ndim))
print(ar.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [9 2 5 7]]]
<class 'int'>
3


In [60]:
import numpy as np

ar = np.array([1,2,3,4], ndmin=10)
print(ar)
print(ar.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [1]:
%timeit [j**4 for j in range(1,9)]

1.51 μs ± 35.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
import numpy as np
%timeit np.arange(1,9)**4

4.51 μs ± 449 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Creating Numpy Arrays

In [8]:
import numpy as np
a = np.array([1,2,3])
print(a)


[1 2 3]


In [12]:
import numpy as np
x = [1,2,3,4,5,6]
y = np.array(x)
print(y)

[1 2 3 4 5 6]


In [4]:
import numpy as np

l = []
for i in range(1, 9):
    int_l = int(input("Enter a number: "))
    l.append(int_l)

print(np.array(l))


Enter a number:  22
Enter a number:  21
Enter a number:  23
Enter a number:  24
Enter a number:  34
Enter a number:  44
Enter a number:  33
Enter a number:  54


[22 21 23 24 34 44 33 54]


In [10]:
ae = np.array([[1,2,3,4],[5,6,7,8]])
print(ae)
print(ae.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


## create Numpy array using Numpy functions

### spacial numpy array

### Zeros

In [22]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones

In [25]:
arr_one = np.ones(4)
print(arr_one)

[1. 1. 1. 1.]


### Empty

In [28]:
ar_empty = np.empty(4)
print(ar_empty)

[1. 1. 1. 1.]


### Range

In [33]:
ar_rn  = np.arange(4)
print(ar_rn)

[0 1 2 3]


### daigonal 

In [36]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## line space

In [45]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# NumPy Array Random Numbers

### Random

### Rand

In [51]:
import numpy as np
var = np.random.rand(3)
print(var)

[0.6584272  0.03645851 0.26613808]


In [53]:
import numpy as np
var1 = np.random.rand(3,5)
print(var1)

[[0.95974059 0.69046436 0.60654366 0.70447702 0.76319527]
 [0.04305017 0.35516274 0.14934367 0.19829188 0.62162434]
 [0.43928541 0.48936869 0.3290529  0.62059998 0.49082136]]


## Randn()

In [58]:
var2 = np.random.randn(3)
print(var2)

[ 0.05582706 -0.97908833 -1.6971719 ]


## Ranf ()

In [62]:
var3 = np.random.ranf(4)
print(var3)

[0.7571316  0.87136302 0.1600587  0.44523135]


## Randint ()

In [67]:
var4 = np.random.randint(5,20,5)
print(var4)

[ 5  5 12 18 11]


# Data Types in numpy array

## Data Type

In [73]:
import numpy as np
var = np.array([1,2,3,4,12,13,14])
print("Data Type",var.dtype)

Data Type int32


In [75]:
import numpy as np
var = np.array([1.0,3.3,4.2,2.0])
print("Data Type",var.dtype)

Data Type float64


In [79]:
import numpy as np
var = np.array(['a','p','p','l','e',1,2,3,4,5])
print("Data Type",var.dtype)

Data Type <U11


In [87]:
x = np.array([1,2,3,4])
print(x)
print("Data Type",x.dtype)

[1 2 3 4]
Data Type int32


In [85]:
x = np.array([1,2,3,4],dtype = np.int8)
print(x)
print("Data Type",x.dtype)

[1 2 3 4]
Data Type int8


In [91]:
x1 = np.array([1,2,3,4],dtype = "f")
print(x1)
print("Data Type",x1.dtype)

[1. 2. 3. 4.]
Data Type float32


In [99]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
print(x2)
print(new)
print("Data Type",x2.dtype)
print("Data Type",new.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
Data Type int32
Data Type float32


In [103]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_1 = np.int_(new)
print(x2)
print(new)
print(new_1)

print("Data Type",x2.dtype)
print("Data Type",new.dtype)
print("Data Type",new_1.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]
Data Type int32
Data Type float32
Data Type int32


In [105]:
x3 = np.array([1,2,3,4])

new_one = x3.astype(float)
print(x3)
print(new_one)

[1 2 3 4]
[1. 2. 3. 4.]


# shape & reshaping

## Shape

In [111]:
import numpy as np
varr = np.array([[1,2],[1,2]])
print(varr)
print()
print(varr.shape)

[[1 2]
 [1 2]]

(2, 2)


In [113]:
import numpy as np
varr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(varr)
print()
print(varr.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]

(2, 5)


In [19]:
var = np.array([1,2,3,4],ndmin=4)

print(var)
print()

print(var.ndim)
print()

print(var.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


## Reshape

In [20]:
var1 = np.array([1,2,3,4,5,6])
print(var1)
print()

print(var1.ndim)
print()

x = var1.reshape(3,2)
print(x)
print()

print(x.ndim)

[1 2 3 4 5 6]

1

[[1 2]
 [3 4]
 [5 6]]

2


In [136]:
import numpy as np

var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print(var2.ndim)
print()

x1 = var2.reshape(3, 3)  # ✅ 3 × 3 = 9
print(x1)
print(x1.ndim)


[1 2 3 4 5 6 1 2 3]
1

[[1 2 3]
 [4 5 6]
 [1 2 3]]
2


In [138]:
import numpy as np

var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x2 = var3.reshape(2, 3, 2)  
print(x2)
print(x2.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [142]:
import numpy as np

var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(2, 3, 2)  
print(x1)
print(x1.ndim)
print()
one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Numpy Arithmetic Operations

# Numpy Arithmetic Operations

In [145]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [145]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [165]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])


varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [163]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])


varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [161]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,3)
print(varadd)

[4 5 6 7]


In [149]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var - 3
print(varadd)

[-2 -1  0  1]


In [151]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var * 3
print(varadd)

[ 3  6  9 12]


In [153]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [155]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var % 3
print(varadd)

[1 2 0 1]


## 2-D Array

In [172]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
varadd2 = var21 + var22
print(var22)
print()

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


# Numpy Arithmetic Functions

In [179]:
import numpy as np
var = np.array([1,2,3,4,5,6,2,3,4])
print(np.min(var))

1


In [181]:
import numpy as np
var = np.array([1,2,3,4,5,6,2,3,4])
print(np.max(var))

6


In [183]:
import numpy as np
var = np.array([1,2,3,4])
print("min:",np.min(var))
print("max:",np.max(var))


min: 1
max: 4


In [17]:
import numpy as np
var = np.array([1,2,3,4])
print("min:",np.min(var),np.argmin(var))
print("max:",np.max(var),np.argmax(var))
print("sqrt",np.sqrt(var))

min: 1 0
max: 4 3
sqrt [1.         1.41421356 1.73205081 2.        ]


In [18]:
var1 = np.array([[2,1,3],[9,5,7]])
print(np.min(var1,axis=0))
print(np.min(var1,axis=1))

[2 1 3]
[1 5]


In [25]:
var2  = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [23]:
var21  = np.array([45,60,30])
print(np.sin(var21))
print(np.cos(var21))

[ 0.85090352 -0.30481062 -0.98803162]
[ 0.52532199 -0.95241298  0.15425145]


# Broadcasting  

In [38]:
import numpy as np

var1 = np.array([1,2,3,4]) 

var2 = np.array([1,2,3,5]) 

print(var1+ var2)

[2 4 6 9]


In [36]:
import numpy as np
var1 = np.array([1,2,3,4]) 
print(np.shape)

var2 = np.array([1,2,3,5]) 
print(np.shape)

print(var1+ var2)

<function shape at 0x00000215A0D7AA20>
<function shape at 0x00000215A0D7AA20>
[2 4 6 9]


In [53]:
import numpy as np
var1 = np.array([1,2,3,4]) 
print(var1.shape)
print()
print(var1)
print()

var2 = np.array([[1],[2],[3],[5]]) 
print()

print(var2)
print()

print(var2.shape)
print()

print(var1+ var2)

(4,)

[1 2 3 4]


[[1]
 [2]
 [3]
 [5]]

(4, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [6 7 8 9]]


In [21]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print()


print(x + y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing Nummpy Array

In [70]:
import numpy as np
var = np.array([8,5,6,7,9])
print(var[3])
print(var[-4])

7
5


In [22]:
var1 = np.array([[5,8,4],[2,4,8]])
print(var1)
print(var1.ndim)
print()
print(var1[0,1])
print()

print(var1[1,1])


[[5 8 4]
 [2 4 8]]
2

8

4


In [23]:
var2 = np.array([[[5,8,4],[2,4,8],[7,4,5]]])
print(var2)
print()

print(var2.ndim)
print()

print(var2[0,1,2])

[[[5 8 4]
  [2 4 8]
  [7 4 5]]]

3

8


# Slicing

In [24]:
import numpy as np
x = np.array([1,2,3,4,5,6,7])
print(x)
print()
print("2 to 5 ",x[1:4])
print()

print("2 to end ",x[1:])
print()

print("start to 5 ",x[:5])
print()

print("stop ",x[1:5:2])
print()

print("stop:" , x[::2])

[1 2 3 4 5 6 7]

2 to 5  [2 3 4]

2 to end  [2 3 4 5 6 7]

start to 5  [1 2 3 4 5]

stop  [2 4]

stop: [1 3 5 7]


In [27]:
var = np.array([[7,6,5,4],[9,3,5,6],[11,12,13,14]])
print(var)
print()

print("8 to 5 :",var[2,1:])

print("6 to 9 :",var[1,1:])

print("6 to 9 :",var[0,1:])

[[ 7  6  5  4]
 [ 9  3  5  6]
 [11 12 13 14]]

8 to 5 : [12 13 14]
6 to 9 : [3 5 6]
6 to 9 : [6 5 4]


# Iteration

In [22]:
import numpy as pd
x = np.array([9,6,7,4,5,3])
print(x)

for i in x :
    print(i)

[9 6 7 4 5 3]
9
6
7
4
5
3


In [42]:
import numpy as np

var = np.array([[2,6,5,3],[6,5,9,5]])
print(var)
print()

for i in var:
    print(i)
    print()
    for j in var:
        for l in j:
            print(l)


[[2 6 5 3]
 [6 5 9 5]]

[2 6 5 3]

2
6
5
3
6
5
9
5
[6 5 9 5]

2
6
5
3
6
5
9
5


In [44]:
import numpy as np

var = np.array([[2,6,5,3],[6,5,9,5]])
print(var)
print()

for i in var:
    print(i)
    print()
    for j in var:
        for l in j:
            print(l)


[[2 6 5 3]
 [6 5 9 5]]

[2 6 5 3]

2
6
5
3
6
5
9
5
[6 5 9 5]

2
6
5
3
6
5
9
5


In [29]:
var2 = np.array([[[6,4,7,2],[6,3,2,2],[8,3,7,3]]])
print(var2)
print()

print(var2.ndim)
print()
for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[6 4 7 2]
  [6 3 2 2]
  [8 3 7 3]]]

3

6
4
7
2
6
3
2
2
8
3
7
3


In [46]:
import numpy as np

# 3D array: shape (2, 2, 4)
# → 2 "blocks", each block has 2 rows × 4 columns
var = np.array([
    [[2, 6, 5, 3],
     [6, 5, 9, 5]],
    
    [[1, 2, 3, 4],
     [7, 8, 9, 0]]
])

print("3D Array:\n", var)
print("\nShape:", var.shape)
print()

# Loop through the 3D array
for block in var:                # 1st dimension
    print("Block:\n", block)
    print()
    for row in block:            # 2nd dimension
        print("Row:", row)
        for elem in row:         # 3rd dimension
            print("Element:", elem)
        print()


3D Array:
 [[[2 6 5 3]
  [6 5 9 5]]

 [[1 2 3 4]
  [7 8 9 0]]]

Shape: (2, 2, 4)

Block:
 [[2 6 5 3]
 [6 5 9 5]]

Row: [2 6 5 3]
Element: 2
Element: 6
Element: 5
Element: 3

Row: [6 5 9 5]
Element: 6
Element: 5
Element: 9
Element: 5

Block:
 [[1 2 3 4]
 [7 8 9 0]]

Row: [1 2 3 4]
Element: 1
Element: 2
Element: 3
Element: 4

Row: [7 8 9 0]
Element: 7
Element: 8
Element: 9
Element: 0



In [60]:
import numpy as np

var2 = np.array([[[6,4,7,2],[6,3,2,2],[8,3,7,3]]])
print(var2)
print(var2.ndim)
print()

# Corrected line — use "S" or "U" instead of "s"
#for i in np.nditer(var2, flags=["buffered"], op_dtypes=["S"]):
for i in np.nditer(var2):
    print(i)


[[[6 4 7 2]
  [6 3 2 2]
  [8 3 7 3]]]
3

6
4
7
2
6
3
2
2
8
3
7
3


In [68]:
import numpy as np

var2 = np.array([[[6,4,7,2],[6,3,2,2],[8,3,7,3]]])
print(var2)
print(var2.ndim)
print()
for i,d in np.ndenumerate(var2):
    print(i,d)

[[[6 4 7 2]
  [6 3 2 2]
  [8 3 7 3]]]
3

(0, 0, 0) 6
(0, 0, 1) 4
(0, 0, 2) 7
(0, 0, 3) 2
(0, 1, 0) 6
(0, 1, 1) 3
(0, 1, 2) 2
(0, 1, 3) 2
(0, 2, 0) 8
(0, 2, 1) 3
(0, 2, 2) 7
(0, 2, 3) 3


# the Difference between copy and view

In [30]:
import numpy as np

var = np.array([1,2,3,4])
co = var.copy()
var[1]=30
print("var",var)
print("copy",co)

var [ 1 30  3  4]
copy [1 2 3 4]


In [79]:
x = np.array([8,6,9,5,3,7])
vi = x.view()
x[1]=30

print("x",x)
print("view",vi)

x [ 8 30  9  5  3  7]
view [ 8 30  9  5  3  7]


# join 

In [82]:
import numpy as np
x = np.array([3,5,6])
x1 = np.array([5,2,8])
ar = np.concatenate((x,x1))
print(ar)

[3 5 6 5 2 8]


In [88]:
import numpy as np
y = np.array([[3,5],[7,6]])
z = np.array([[5,2],[8,1]])
ar_new = np.concatenate((y,z),axis=1)
ar_new = np.concatenate((y,z),axis=0)
print(y)
print()
print(z)
print()
print(ar_new)


[[3 5]
 [7 6]]

[[5 2]
 [8 1]]

[[3 5]
 [7 6]
 [5 2]
 [8 1]]


In [98]:
y = np.array([3,5,7,6])
z = np.array([5,2,8,1])

ar = np.stack((y,z),axis = 1)

ar1 = np.hstack((y,z))  #roows

ar2 = np.vstack((y,z))    #columns

ar3 = np.dstack((y,z))  # height

print(ar)
print()

print(ar1)
print()
print(ar2)
print()

print(ar3)



[[3 5]
 [5 2]
 [7 8]
 [6 1]]

[3 5 7 6 5 2 8 1]

[[3 5 7 6]
 [5 2 8 1]]

[[[3 5]
  [5 2]
  [7 8]
  [6 1]]]


# Split

In [107]:
import numpy as np
v = np.array([6,3,5,6,2,4,3,4])
print(v)
a = np.array_split(v,3)
print()
print(a)
print(a[0])
print(a[1])

print(a[2])
print(type(a))

[6 3 5 6 2 4 3 4]

[array([6, 3, 5]), array([6, 2, 4]), array([3, 4])]
[6 3 5]
[6 2 4]
[3 4]
<class 'list'>


In [113]:
import numpy as np
v1 = np.array([[6,3,5,6],[2,4,3,4]])
print(v1)
a = np.array_split(v1,3)
a2 = np.array_split(v1,3,axis=1)
print()
print(a)
print()
print(a2)
print()
print(a[0])
print()
print(a[1])
print(a[2])
print(type(a))

[[6 3 5 6]
 [2 4 3 4]]

[array([[6, 3, 5, 6]]), array([[2, 4, 3, 4]]), array([], shape=(0, 4), dtype=int32)]

[array([[6, 3],
       [2, 4]]), array([[5],
       [3]]), array([[6],
       [4]])]

[[6 3 5 6]]

[[2 4 3 4]]
[]
<class 'list'>


# Search, Sort, Search Shorted, Filter Functions

##   Search

In [125]:
import numpy as np
a = np.array([1,2,4,6,7,8])
x = np.where(a == 2)
x = np.where( (a/2) == 0)
x = np.where( (a%2) == 0)
print(a)
print()
print(x)

[1 2 4 6 7 8]

(array([1, 2, 3, 5], dtype=int64),)


# Search Sort

In [140]:
import numpy as np
a1= np.array([1,2,4,6,7,8,9])
x1 = np.searchsorted(a1, 5,side="right")
x1 = np.searchsorted(a1, [5,10,0],side="left")
print(x1)

[3 7 0]


# sort

In [145]:
import numpy as np
b = np.array([1,2,4,6,7,8])
y = np.sort( (b) )
print(y)

[1 2 4 6 7 8]


In [13]:
import numpy as np
b = np.array([[1,2,4,6,7,8],[9,3,4,5,6,7]])
y = np.sort( (b) )
print(y)

[[1 2 4 6 7 8]
 [3 4 5 6 7 9]]


In [11]:
import numpy as np
var_1 = np.array(['k', 'a', 'n', 'n', 'u'])
print(np.sort(var_1))


['a' 'k' 'n' 'n' 'u']


## Filter

In [24]:
import numpy as np
a = np.array(['k', 'a', 'n', 'n', 'u'])
f = [True, False, True, False, True]  
b = a[f]
print(b)
print(type(b))


['k' 'n' 'u']
<class 'numpy.ndarray'>


# Functions

### Shuffle

In [30]:
import numpy as np
a = np.array([1,2,3,4,5,6])
np.random.shuffle(a)
print(a)

[4 1 6 3 2 5]


## Unique

In [33]:
v = np.array([1,23,45,1,2,3,4,4])
x = np.unique(v)
print(x)

[ 1  2  3  4 23 45]


In [37]:
v = np.array([1,23,45,1,2,3,4,4])
x = np.unique(v,return_index=True,return_counts=True)
print(x)

(array([ 1,  2,  3,  4, 23, 45]), array([0, 4, 5, 6, 1, 2], dtype=int64), array([2, 1, 1, 2, 1, 1], dtype=int64))


## Resize

In [44]:
x = np.array([1,23,45,1,2,3,4,4])
v = np.resize(x,(3,2))
print(v)


[[ 1 23]
 [45  1]
 [ 2  3]]


## Flatten

In [49]:
import numpy as np
x = np.array([1,23,45,1,2,3,4,4])
v = np.resize(x,(3,2))
print(v)
print()
print(v.flatten())


[[ 1 23]
 [45  1]
 [ 2  3]]

[ 1 23 45  1  2  3]


In [53]:
import numpy as np
x = np.array([1,23,45,1,2,3,4,4])
v = np.resize(x,(3,2))
print(v)
print()
print(v.flatten(order='C'))
print('Ravel ',np.ravel(y,order='A'))

[[ 1 23]
 [45  1]
 [ 2  3]]

[ 1 23 45  1  2  3]
Ravel  [1 2 4 6 7 8 3 4 5 6 7 9]


# Insert

In [60]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print()
print(type(a))
print()
v = np.insert(a,(2,3),40)

print(v)


[1 2 3 4]

<class 'numpy.ndarray'>

[ 1  2 40  3 40  4]


In [5]:
import numpy as np
a = np.array([[1,2,3,4],[8,6,5,4]])
print(a)
print(type(a))
print()

v = np.insert(a, 2,  6, axis=0)
print(v)


[[1 2 3 4]
 [8 6 5 4]]
<class 'numpy.ndarray'>

[[1 2 3 4]
 [8 6 5 4]
 [6 6 6 6]]


In [9]:
import numpy as np
a = np.array([[1,2,3,4],[8,6,5,4]])
print(a)
print(type(a))
print()

v = np.insert(a, 2, [22, 66], axis=1)
print(v)


[[1 2 3 4]
 [8 6 5 4]]
<class 'numpy.ndarray'>

[[ 1  2 22  3  4]
 [ 8  6 66  5  4]]


## Delete

In [11]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
v = np.delete(a,2)
print(v)

[1 2 3 4]
[1 2 4]


## Matrix

In [4]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [8]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


## Arithmetic Operation in matrix

# Add

In [14]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var)
print()
print(var + var1)

[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [2 4 6]]


# Sub

In [17]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var)
print()
print(var - var1)

[[1 2 3]
 [1 2 3]]

[[0 0 0]
 [0 0 0]]


## Multiply

In [29]:
import numpy as np

var = np.matrix([1, 2, 3])
var1 = np.matrix([[6], [7], [8]])

print(var)
print()
print(var * var1)
print()
print(var.dot(var1))


[[1 2 3]]

[[44]]

[[44]]


In [33]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print()

print(type(var1))
print()

print(var1*var1)

[[1 2 3]
 [1 2 3]]

<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


# Matrix Function

## Transpose

In [43]:
import numpy as np
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var1)
print()
print(np.transpose(var1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


In [45]:
import numpy as np
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var1)
print()
print(var1.T)


[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


## Swapaxes

In [47]:
import numpy as np
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var1)
print()
print(np.swapaxes(var1,0,1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


In [51]:
import numpy as np
var1 = np.matrix([[1,2,3],[5,4,3]])
print(var1)
print()
print(np.swapaxes(var1,0,1))
print()

[[1 2 3]
 [5 4 3]]

[[1 5]
 [2 4]
 [3 3]]



## Inverse

In [55]:
import numpy as np

var1 = np.matrix([[1, 2], [3, 4]])
print(var1)
print()
print(np.linalg.inv(var1))


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


## Power

In [61]:
import numpy as np

var1 = np.matrix([[1, 2], [3, 4]])
print(var1)
print()
print(np.linalg.matrix_power(var1,3))
print()
print(np.linalg.matrix_power(var1,0))


[[1 2]
 [3 4]]

[[ 37  54]
 [ 81 118]]

[[1 0]
 [0 1]]


## Determinate

In [69]:
import numpy as np

var1 = np.matrix([[1, 2], [3, 4]])
print(var1)
print()
print(np.dot(var1, var1))   # or simply var1 * var1


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]


# Data type

In [5]:
import numpy as np
var = np.array([1,2,3,4,5])

print('Data Type: ',var.dtype)

Data Type:  int64


In [6]:
var = np.array([1.755,2.675,3.987,4.422,5.654])
print('Data Type: ',var.dtype)

Data Type:  float64


In [7]:
var = np.array(["P","y","t","h","o","n"])

print('Data Type: ',var.dtype)

Data Type:  <U1


In [8]:
var = np.array(["P","y","t","h","o","n",1,2,3,4])

print('Data Type: ',var.dtype)

Data Type:  <U21


In [11]:
x = np.array([1,2,3,4],dtype=np.int8)

print('Data Type: ',x.dtype)

print(x)

Data Type:  int8
[1 2 3 4]


In [12]:
x1 = np.array([1,2,3,4],dtype= 'f')

print('Data Type: ',x1.dtype)

print(x1)

Data Type:  float32
[1. 2. 3. 4.]


In [13]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

print('Data Type: ',x2.dtype)
print('Data Type: ',new.dtype)
print(x2)
print(new)

Data Type:  int64
Data Type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [15]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new1 = np.int_(new)

print('Data Type: ',x2.dtype)

print('Data Type: ',new.dtype)

print('Data Type: ',new1.dtype)


print(x2)

print(new)

print(new1)

Data Type:  int64
Data Type:  float32
Data Type:  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [17]:
x3 = np.array([1,2,3,4])
new2 = x3.astype(float)

print(x3)

print(new2)

[1 2 3 4]
[1. 2. 3. 4.]
