In [1]:
#  WHAT IS NUMPY?
Numpy is a Python external library that helps us perform various scientific Computations and allows us to work
with multidimensional arrays more efficiently.
After learning that Numpy is used to working with multidimensional arrays you might wonder
why we use this external library if we have a Python list. We can also use List to work with multidimensional arrays.
So, this is a very valid question. I will tell you why we use numpy if we have a Python list. let’s explore the difference.

**CREATE NUMPY ARRAY**

In [1]:
import numpy as np
my_array = np.array([1,2,3,4,5,6,7])
print(my_array)

[1 2 3 4 5 6 7]


In [4]:
import numpy as np
my_array = np.array([1,2,3,4,5,6,7])
my_array
print(my_array)
print(type(my_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [7]:
l = []

for i in range(1, 5):
    int_1 = int(input("Enter :"))
    l.append(int_1)

print(np.array(l))

Enter : 12113
Enter : 21344
Enter : 21234
Enter : 2132


[12113 21344 21234  2132]


In [12]:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5]) 
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim) 
print(c.ndim) 
print(d.ndim)

0
1
2
3


In [21]:
import numpy as np
     # 1-D array
a1 = np.array([1,2,3,4,5,6])
print(a1)
     # 2=D array
a2 = np.array([[1,2,3,4,5]])
print(a2)
   # 3-D array
a3 = np.array([[[1,2,3,4,5]]])
print(a3)

[1 2 3 4 5 6]
[[1 2 3 4 5]]
[[[1 2 3 4 5]]]


 **1D array**

In [13]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)

print(x3)

print(new_1)


[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
import numpy as np
arr1 = np.array([6,5,3,4])
print(f'1D Array:{arr1}')
print(f'dimention:{arr1.ndim}')

1D Array:[6 5 3 4]
dimention:1


In [9]:
import numpy as np
arr1 = np.array([6,5,3,4])
print(arr1)
print(arr1.ndim)

[6 5 3 4]
1


### 2D array

In [16]:
import numpy as np
arr2 = np.array([[1,2,3,4],[6,7,8,9]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [6 7 8 9]]
2


### 3D array

In [19]:
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


### higher dimentional array

In [30]:
import numpy as np
arr = np.array([1,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 3 4 5]]]]]
5


In [32]:
arr = np.array([1,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 3 4 5]]]]]
5


# array fileds with zeros

In [35]:
import numpy as np
arr_zero = np.zeros(4)
print(arr_zero)

[0. 0. 0. 0.]


In [37]:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [41]:
arr = np.array([1,2,3,4])
print(arr[2]+ arr[3]) 

7


In [43]:
import numpy as np
arr_zero2 = np.zeros((3,4))
print(arr_zero2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
import numpy as np
arr_ones = np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [51]:
import numpy as np
arr_emp = np.empty(3)
print(arr_emp)

[1.40544824e-311 0.00000000e+000 6.47591605e-319]


In [55]:
import numpy as np
arr_range = np.arange(1,6)
print(arr_range)

[1 2 3 4 5]


In [61]:
import numpy as np
arr_matrix = np.eye(3)
print(arr_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
# linearly in a spacified

In [67]:
import numpy as np
l_space = np.linspace(1,10,num=5)
print(l_space)

[ 1.    3.25  5.5   7.75 10.  ]


# random 

In [72]:
import numpy as np
arr_rand = np.random.rand(5)
print(arr_rand)

[0.84951546 0.36949546 0.85655759 0.71429717 0.35588618]
