In [60]:
import numpy as np


In [61]:
li = [12,23,44,"Kanchan", 53.4]
arr=np.array(li)
arr
arr.dtype

dtype('<U32')

## When we have different data types in list at that time numpy

In [62]:
arr = np.array([12,23,44,"Kanchan", 53.4])
arr

array(['12', '23', '44', 'Kanchan', '53.4'], dtype='<U32')

In [63]:
salary = [10000, 30000, 7000, 89000]

new_salary = []

for s in salary:
    new_salary.append(s + 5000)

print(new_salary)

[15000, 35000, 12000, 94000]


In [65]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [67]:
arr = np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [69]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
np.linspace(1,1000,5)

array([   1.  ,  250.75,  500.5 ,  750.25, 1000.  ])

In [71]:
arr = np.ones((4,4))
print(arr)
arr.shape
arr.size
arr.dtype

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


dtype('float64')

In [72]:
arr1 = np.linspace(1,2,4)
print(arr1)

arr1.size
arr1.dtype

[1.         1.33333333 1.66666667 2.        ]


dtype('float64')

In [73]:
arr=np.array([12,22,33,44,56,70])
arr
np.sum(arr)
print(np.mean(arr))

print(np.mean)

39.5
<function mean at 0x0000021569BBB880>


In [74]:


arr = np.array([12,22,33,44,56,70])

mean = np.mean(arr[1:4])

np.std(arr)

np.float64(19.69560018548982)

In [75]:
arr = np.array([12, 22, 33, 44, 56, 70])

std = np.std(arr)

print(std)

19.69560018548982


In [76]:
a1=np.array([91,23,4,5])
a2=np.array([12,8,4,2])
 
print(a1 + a2)
print(a1*a2)

[103  31   8   7]
[1092  184   16   10]


In [77]:
salary = np.array([10000, 12000, 15000, 18000, 20000,
                   22000, 25000, 27000, 30000, 32000, 35000])

salary = salary * 0.11

print(salary)

[1100. 1320. 1650. 1980. 2200. 2420. 2750. 2970. 3300. 3520. 3850.]


In [78]:
arr = np.random.rand(5)
arr

array([0.66529791, 0.55862089, 0.21134905, 0.56039962, 0.85662674])

In [80]:
np.random.randint(1,100)

48

In [81]:
import numpy as np

marks = np.random.randint(0, 101, 6)

for i in range(6):
    print("Student", i + 1, ":", marks[i])

Student 1 : 49
Student 2 : 68
Student 3 : 36
Student 4 : 32
Student 5 : 35
Student 6 : 30


In [82]:
print(np.random.randint(1,101,6))

[39 65 52 51 46 81]


In [83]:
marks = np.random.randint(1, 101, 6)

marks = marks + 10

print(np.random.randint(1,101,6))
print(marks)

[85 19  3 20 16 63]
[108  87  79  45  12  25]


In [84]:
import numpy as np

marks = np.random.randint(1, 101, 6)

marks = marks + 10

total = np.sum(marks)

percentage = (total / 600) * 100

print("Marks:", marks)
print("Total:", total)
print("Percentage:", percentage)

Marks: [100  52  62  68  94 103]
Total: 479
Percentage: 79.83333333333333
